# Generated by Django 5.2.17 on 2026-08-11 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('infrastructure', '0002_client_server_connection_method_server_credential_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PLAYBOOK', 'Playbook'), ('CONNECTION_TEST', 'Connection test')], default='PLAYBOOK', max_length=20)),
                ('playbook', models.CharField(blank=True, max_length=200)),
                ('limit', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('extra_vars', models.JSONField(blank=True, default=dict)),
                ('check_mode', models.BooleanField(default=False, help_text='Dry run. Ansible reports what would change, and changes nothing.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('TIMEOUT', 'Timeout')], db_index=True, default='PENDING', max_length=16)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('recap', models.JSONField(blank=True, default=dict)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='infrastructure.client')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='credentials.credential')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='infrastructure.environment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='infrastructure.servergroup')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_requested', to=settings.AUTH_USER_MODEL)),
                ('servers', models.ManyToManyField(blank=True, related_name='jobs', to='infrastructure.server')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='jobs_job_status_57b86b_idx'), models.Index(fields=['kind', '-created_at'], name='jobs_job_kind_3b90ad_idx')],
            },
        ),
    ]
