# Generated by Django 5.2.17 on 2026-08-11 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('SSH_PRIVATE_KEY', 'SSH private key'), ('SSH_PASSWORD', 'SSH password'), ('BECOME_PASSWORD', 'Become (sudo) password')], max_length=32)),
                ('username', models.CharField(blank=True, help_text='Remote user this credential authenticates as, when applicable.', max_length=64)),
                ('encrypted_secret', models.TextField(editable=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credential',
                'verbose_name_plural': 'credentials',
                'ordering': ['name'],
                'permissions': [('use_credential', 'Can use a credential to connect, without reading its secret')],
                'indexes': [models.Index(fields=['type'], name='credentials_type_b4cdcd_idx')],
            },
        ),
    ]
