# Generated by Django 5.2.17 on 2026-08-11 13:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('require_check_mode', models.BooleanField(default=False, help_text='Only allow check-mode (dry run) executions against this environment.')),
            ],
            options={
                'verbose_name': 'environment',
                'verbose_name_plural': 'environments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'server group',
                'verbose_name_plural': 'server groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Inventory hostname, e.g. web01.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hostname', models.CharField(blank=True, help_text='DNS name, if the host has one.', max_length=253)),
                ('primary_ip', models.GenericIPAddressField(blank=True, help_text='Used as ansible_host when set.', null=True)),
                ('ssh_port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('ansible_user', models.CharField(default='ansible', max_length=64)),
                ('operating_system', models.CharField(choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('AIX', 'AIX'), ('OTHER', 'Other')], default='LINUX', max_length=16)),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERROR', 'Error')], default='UNKNOWN', max_length=16)),
                ('last_connection_test', models.DateTimeField(blank=True, null=True)),
                ('last_successful_connection', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers_created', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='infrastructure.environment')),
                ('groups', models.ManyToManyField(blank=True, related_name='servers', to='infrastructure.servergroup')),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='infrastruct_status_720a38_idx'), models.Index(fields=['environment', 'name'], name='infrastruct_environ_f15eae_idx'), models.Index(fields=['active'], name='infrastruct_active_70416c_idx')],
            },
        ),
    ]
