# Generated by Django 5.2.17 on 2026-08-11 13:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='server',
            name='connection_method',
            field=models.CharField(choices=[('SSH', 'SSH'), ('WINRM', 'WinRM'), ('AGENT', 'Agent (planned)')], default='SSH', max_length=16),
        ),
        migrations.AddField(
            model_name='server',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='Credential used to connect. The secret is never exposed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='credentials.credential'),
        ),
        migrations.AlterField(
            model_name='server',
            name='operating_system',
            field=models.CharField(choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('AIX', 'AIX'), ('SOLARIS', 'Solaris'), ('HPUX', 'HP-UX'), ('BSD', 'BSD'), ('MACOS', 'macOS'), ('NETWORK', 'Network device'), ('OTHER', 'Other')], default='LINUX', max_length=16),
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22, help_text='Connection port. Defaults to 22 (SSH) or 5986 (WinRM).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='port'),
        ),
        migrations.AddField(
            model_name='server',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='infrastructure.client'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['client', 'name'], name='infrastruct_client__bb4108_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['connection_method'], name='infrastruct_connect_ef94fa_idx'),
        ),
    ]
