# Generated by Django 5.2.17 on 2026-08-11 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('FAILED_LOGIN', 'Failed login'), ('BLOCKED_IP', 'Blocked IP'), ('SUSPICIOUS_ACTIVITY', 'Suspicious activity'), ('POLICY_CHANGE', 'Policy change'), ('SESSION_EVENT', 'Session event')], db_index=True, max_length=32)),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security event',
                'verbose_name_plural': 'security events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'event_type'], name='security_se_created_94398a_idx'), models.Index(fields=['severity', '-created_at'], name='security_se_severit_a311e5_idx')],
            },
        ),
    ]
