# Generated by Django 5.2.17 on 2026-08-11 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('asn', models.CharField(blank=True, max_length=32)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=128)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXECUTE', 'Execute'), ('CHECK', 'Check'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('DENIED', 'Denied'), ('EXPORT', 'Export'), ('DOWNLOAD', 'Download')], max_length=16)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DENIED', 'Denied')], default='SUCCESS', max_length=16)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'module'], name='audit_audit_created_ac4602_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_605853_idx'), models.Index(fields=['action', 'result'], name='audit_audit_action_9aa41c_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2ab5ff_idx')],
            },
        ),
    ]
