#!/usr/bin/env bash
#
# Ansible DevOps Platform — bootstrap.
#
# Generates every secret, starts the stack, applies migrations and creates the
# initial administrator.
#
# Idempotent by design: an existing .env is never overwritten, an existing
# database is never destroyed, and an existing admin password is never reset.
# Running this twice is safe.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PAD='........................................'

step()  { printf '[%s] %s %s ' "$1" "$2" "${PAD:${#2}}"; }
ok()    { printf 'OK\n'; }
pass()  { printf 'PASS\n'; }
skip()  { printf 'SKIP (%s)\n' "$1"; }
fail()  { printf 'FAIL\n'; [ $# -gt 0 ] && printf '\n  %s\n' "$1" >&2; exit 1; }

require() {
  step CHECK "$1"
  command -v "$2" >/dev/null 2>&1 || fail "$1 is required but was not found in PATH."
  ok
}

# --------------------------------------------------------------------------
# Prerequisites
# --------------------------------------------------------------------------

require Docker docker
require OpenSSL openssl

step CHECK "Docker Compose"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required (docker compose)."
ok

step CHECK "Docker daemon"
docker info >/dev/null 2>&1 || fail "The Docker daemon is not running."
ok

# --------------------------------------------------------------------------
# Environment — generated once, never regenerated
# --------------------------------------------------------------------------

step BOOT "Environment file"
if [ -f .env ]; then
  skip "existing .env preserved"
  ENV_CREATED=0
else
  # tr '/+' '_-' keeps the values shell- and URL-safe inside .env.
  DJANGO_SECRET_KEY="$(openssl rand -base64 48 | tr -d '\n' | tr '/+' '_-')"
  POSTGRES_PASSWORD="$(openssl rand -base64 32 | tr -d '\n' | tr '/+' '_-')"
  INITIAL_ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '\n' | tr '/+' '_-')"
  PLATFORM_ENCRYPTION_KEY="$(openssl rand -hex 32)"

  umask 077
  cat > .env <<EOF
# Generated by scripts/bootstrap.sh — do not commit this file.
PROJECT_NAME=ansible-devops-platform
PROJECT_ENV=development

DJANGO_DEBUG=True
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
PLATFORM_ENCRYPTION_KEY=${PLATFORM_ENCRYPTION_KEY}

POSTGRES_DB=ansible_platform
POSTGRES_USER=ansible_platform
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_HOST=ansible-postgres
POSTGRES_PORT=5432

REDIS_HOST=ansible-redis
REDIS_PORT=6379

INITIAL_ADMIN_USERNAME=admin
INITIAL_ADMIN_EMAIL=admin@localhost
INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}

ANSIBLE_API_PORT=47420
EOF
  chmod 600 .env
  ENV_CREATED=1
  ok
fi

# --------------------------------------------------------------------------
# Stack
# --------------------------------------------------------------------------

step BOOT "Building images"
docker compose build >/dev/null 2>&1 || fail "Image build failed. Run 'docker compose build' to see why."
ok

step BOOT "PostgreSQL"
docker compose up -d ansible-postgres >/dev/null 2>&1 || fail "Could not start PostgreSQL."
ok

step BOOT "Redis"
docker compose up -d ansible-redis >/dev/null 2>&1 || fail "Could not start Redis."
ok

step BOOT "Django API"
docker compose up -d ansible-api >/dev/null 2>&1 || fail "Could not start the API."
ok

step BOOT "Migrations"
docker compose exec -T ansible-api python manage.py migrate --noinput >/dev/null \
  || fail "Migrations failed. Check 'docker compose logs ansible-api'."
ok

# --------------------------------------------------------------------------
# Administrator — created once; an existing password is never reset
# --------------------------------------------------------------------------

step BOOT "Administrator"
ADMIN_RESULT="$(docker compose exec -T ansible-api python manage.py shell -c '
import os
from django.contrib.auth import get_user_model

User = get_user_model()
username = os.environ.get("INITIAL_ADMIN_USERNAME", "admin")
email = os.environ.get("INITIAL_ADMIN_EMAIL", "admin@localhost")
password = os.environ["INITIAL_ADMIN_PASSWORD"]

user, created = User.objects.get_or_create(
    username=username,
    defaults={"email": email, "is_staff": True, "is_superuser": True},
)
if created:
    user.set_password(password)
    user.save()
    print("CREATED")
else:
    print("EXISTS")
' 2>/dev/null | tr -d '\r\n')" || fail "Could not create the administrator account."

case "$ADMIN_RESULT" in
  *CREATED*) ok ;;
  *EXISTS*)  skip "already exists, password unchanged" ;;
  *)         fail "Unexpected result while creating the administrator." ;;
esac

step BOOT "Celery worker"
docker compose up -d ansible-celery >/dev/null 2>&1 || fail "Could not start the Celery worker."
ok

step BOOT "Celery Beat"
docker compose up -d ansible-celery-beat >/dev/null 2>&1 || fail "Could not start Celery Beat."
ok

# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------

step TEST "Django check"
docker compose exec -T ansible-api python manage.py check >/dev/null || fail "Django system checks failed."
pass

API_PORT="$(grep -E '^ANSIBLE_API_PORT=' .env | cut -d= -f2)"
API_PORT="${API_PORT:-47420}"

step TEST "Health endpoint"
HEALTHY=0
for _ in $(seq 1 30); do
  if curl -fsS "http://localhost:${API_PORT}/api/v1/health/" >/dev/null 2>&1; then
    HEALTHY=1
    break
  fi
  sleep 2
done
[ "$HEALTHY" -eq 1 ] || fail "The health endpoint did not become healthy. Check 'docker compose logs'."
pass

# --------------------------------------------------------------------------
# Summary
# --------------------------------------------------------------------------

echo
docker compose ps
echo
echo "============================================================"
echo " Ansible DevOps Platform is running"
echo "============================================================"
echo " URL     : http://localhost:${API_PORT}"
echo " Admin   : http://localhost:${API_PORT}/admin/"
echo " Health  : http://localhost:${API_PORT}/api/v1/health/"
echo " Username: admin"

if [ "$ENV_CREATED" -eq 1 ]; then
  echo
  echo " The initial password was generated for you and stored in .env"
  echo " as INITIAL_ADMIN_PASSWORD. Read it with:"
  echo
  echo "     grep INITIAL_ADMIN_PASSWORD .env"
  echo
  echo " Change it after your first sign-in. Never commit .env."
else
  echo " Password: unchanged (see INITIAL_ADMIN_PASSWORD in .env)"
fi
echo "============================================================"
