# Generated by Django 5.2.17 on 2026-08-11 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(default=dict)),
                ('is_secret', models.BooleanField(default=False, help_text='Hide this value from listings and API representations.')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'platform setting',
                'verbose_name_plural': 'platform settings',
                'ordering': ['category', 'key'],
                'constraints': [models.UniqueConstraint(fields=('category', 'key'), name='unique_platform_setting')],
            },
        ),
    ]
