# Generated by Django 5.2.17 on 2026-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'playbook',
                'permissions': [('view_playbook', 'Can view playbooks'), ('add_playbook', 'Can create playbooks'), ('change_playbook', 'Can edit playbooks'), ('delete_playbook', 'Can delete playbooks')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
