# Generated by Django 5.2.17 on 2026-08-11 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('asn', models.CharField(blank=True, max_length=32)),
                ('network', models.CharField(blank=True, max_length=128)),
                ('proxy_signal', models.BooleanField(default=False)),
                ('vpn_signal', models.BooleanField(default=False)),
                ('trusted', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'IP intelligence record',
                'verbose_name_plural': 'IP intelligence records',
                'ordering': ['ip'],
                'indexes': [models.Index(fields=['is_private'], name='ipintel_ipi_is_priv_5dd1e8_idx'), models.Index(fields=['trusted'], name='ipintel_ipi_trusted_014f0f_idx')],
            },
        ),
    ]
